version: '3'

services:
  mongodb:
    image: mongo:6.0.12
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo_data:/data/db

  api:
    image: python:3.11  # Use official Python image
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./api:/app  # Mount local ./api directory inside the container at /app
    working_dir: /app  # Set working directory to /app
    environment:
      MONGO_URL: mongodb://root:example@mongodb:27017/?authSource=admin
    command: ["sh", "-c", "sleep 5 && pip install --no-cache-dir -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app"]

